[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/sparkfun/SparkFun_6DoF_ISM330DHCX_Arduino_Library.git
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO
    sparkfun/SparkFun u-blox GNSS Arduino Library